### ISSUE TITLE
Add tallies from TxGml interface

### ISSUE THREAD

**Issue by gonuke** [svalinn/Tech-X-ProjectMgmt#2]
* [ ] confirm that PyNE Tally class supports all necessary tally types [#3]
* [ ] clarify best way to access Tech-X tally def'n [#9]
* [ ] extend PyNE Tally class as necessary [#4]
* [ ] parse tally information from TxGml interface [ #5]
* [ ] store PyNE tally objects in DAGMC/UW2 file [ #6]
